#!/bin/python3

import math
import os
import random
import re
import sys



#
# Complete the 'doubleSize' function below.
#
# The function is expected to return a LONG_INTEGER.
# The function accepts following parameters:
#  1. LONG_INTEGER_ARRAY arr
#  2. LONG_INTEGER b
#

def doubleSize(arr, b):
    # Write your code here
    pool = set(arr)
    while b in pool:
        b *= 2
    return b

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr_count = int(input().strip())

    arr = []

    for _ in range(arr_count):
        arr_item = int(input().strip())
        arr.append(arr_item)

    b = int(input().strip())

    result = doubleSize(arr, b)

    fptr.write(str(result) + '\n')

    fptr.close()
