#!/bin/python

import math
import os
import random
import re
import sys



#
# Complete the 'getMostVisited' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY sprints
#

def getMostVisited(n, sprints):
    arr = [0]*(n+2)
    for i in range(len(sprints)-1):
        start = min(sprints[i], sprints[i+1])
        end = max(sprints[i], sprints[i+1])
        arr[start] += 1
        arr[end + 1] -= 1
    ans = -1
    s = 0
    maxi = -1
    for i in range(1, n+1):
        arr[i] += s
        s = arr[i]
        if s > maxi:
            maxi = s
            ans = i

    return ans

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(raw_input().strip())

    sprints_count = int(raw_input().strip())

    sprints = []

    for _ in xrange(sprints_count):
        sprints_item = int(raw_input().strip())
        sprints.append(sprints_item)

    result = getMostVisited(n, sprints)

    fptr.write(str(result) + '\n')

    fptr.close()
